version: '3.8'

services:
  backend:
    build: .
    container_name: ai-resume-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: resume_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
      timeout: 3s

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - chromadb_data:/chroma
    ports:
      - "8001:8000"

volumes:
  chromadb_data:
  postgres_data:
